In [1]:
import pandas as pd

In [19]:
dg_key = "e297e933c3ad47d71ec1626c299e"
market_type = 'top_20'

names_dict = {'Matt Fitzpatrick': 'Matthew Fitzpatrick',
    'Si Kim': 'Si Woo Kim',
    'Min Lee': 'Min Woo Lee',
    'Byeong An': 'Byeong Hun An',
    'Rooyen Van': 'Erik Van Rooyen',
    'Vince Whaley': 'Vincent Whaley',
    'Kevin Yu': 'Kevin Yu',
    'Kyounghoon Lee': 'Kyoung-Hoon Lee'
             }

# def implied_probability(moneyline_odds):
#     """
#     Calculate the implied probability from moneyline odds.
#     """
#     # Convert negative odds to positive for calculation
#     if moneyline_odds < 0:
#         moneyline_odds = abs(moneyline_odds) + 100
    
#     # Calculate implied probability
#     implied_prob = 100 / (moneyline_odds + 100)
    
#     # Return implied probability as percentage
#     return implied_prob

def implied_probability(moneyline_odds):
    """
    Calculate the implied probability from moneyline odds.
    """
    # Convert negative odds to positive for calculation
    if moneyline_odds < 0:
        implied_prob = abs(moneyline_odds) / (abs(moneyline_odds) + 100)
    else:
        implied_prob = 100 / (moneyline_odds + 100)
    
    # Return implied probability as percentage
    return implied_prob

def fix_names(list_of_player_names):
    
    # swaps last/first into first/last name
    names = list_of_player_names.str.split(expand=True)                  
    names[0] = names[0].str.rstrip(",")
    names[1] = names[1].str.rstrip(",")
    names['player_name'] = names[1] + " " + names[0]

    # uses dictionary to correct known problem names
    # ie "Jr" or "Si Woo Kim")
#     for incorrect_name, correct_name in names_dict.items():
#         names['player_name'] = np.where(names['player_name'] == incorrect_name, correct_name, names['player_name'])

    return names.player_name

def plus_prefix(a):
    if a > 0:
        return f"+{a}"
    return a

def get_ev_table(market_type):

    # constants
    dg_outrights_data = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key={dg_key}")
    books = ['betmgm', 'draftkings', 'bovada', 'betway','caesars']

    # dg and book aggregates in moneyline form for all players all markets
    real_odds = dg_outrights_data[['player_name','datagolf_base_history_fit']]
    agg_lines = dg_outrights_data[books].T.mean().to_frame() 
    dg_odds = pd.merge(real_odds, agg_lines, left_index=True, right_index=True) 

    # dg decimal odds for calculating ev
    dec_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key={dg_key}",usecols=['player_name','datagolf_base_history_fit'])

    # merge
    df = pd.merge(dg_odds,dec_odds,left_index=True, right_index=True).T.drop_duplicates().T

    df.columns = ['player_name','real_odds','agg_line','euro_line']
    df = df.dropna()

    df['implied_prob'] = 1 / df['euro_line']
    df['ev'] = df['implied_prob'] * df['euro_line'] -1
    df = df[['player_name','real_odds','agg_line','ev']].convert_dtypes()#.round(2)

    return df

In [2]:
dg_key = "e297e933c3ad47d71ec1626c299e"
market_type = 'top_20'

dg_outrights_data = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key={dg_key}")
dg_outrights_data

,dg_id,fanduel,betfair,pointsbet,draftkings,player_name,caesars,williamhill,datagolf_baseline,datagolf_base_history_fit,unibet,last_updated,event_name,market
0,18417,-20000.0,NaN,-14925.0,-20000.0,"Scheffler, Scottie",-10000.0,-10000.0,NaN,-9358.0,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
1,19841,-1600.0,-2500.0,-1600.0,-1600.0,"DeChambeau, Bryson",-1667.0,-2500.0,NaN,-2577.0,-5000.0,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
2,17538,-1800.0,-2000.0,-1799.0,-1800.0,"Homa, Max",-1667.0,-2000.0,NaN,-1516.0,-3333.0,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
3,22085,-700.0,-769.0,-700.0,-700.0,"Morikawa, Collin",-714.0,-714.0,NaN,-509.0,-500.0,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
4,23950,-500.0,-588.0,-500.0,-500.0,"Aberg, Ludvig",-500.0,-500.0,NaN,-374.0,-500.0,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,12422,NaN,NaN,NaN,NaN,"Johnson, Dustin",NaN,NaN,NaN,NaN,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
85,12577,NaN,NaN,NaN,NaN,"Woodland, Gary",NaN,NaN,NaN,NaN,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
86,6093,NaN,NaN,NaN,NaN,"Rose, Justin",NaN,NaN,NaN,NaN,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
87,22760,NaN,NaN,NaN,NaN,"Hisatsune, Ryo",NaN,NaN,NaN,NaN,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20
88,12808,NaN,NaN,NaN,NaN,"Grillo, Emiliano",NaN,NaN,NaN,NaN,NaN,2024-04-13 02:51:55 UTC,Masters Tournament,top_20

In [ ]:
# read in and concat real_odds, agg_line, and euro_line (for ev calc)

# constants
books = ['betmgm', 'draftkings', 'bovada', 'betway','caesars']

# api calls
real_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key=e297e933c3ad47d71ec1626c299e",usecols=['player_name','datagolf_base_history_fit'])
agg_lines = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key=e297e933c3ad47d71ec1626c299e",usecols=books).T.mean().to_frame()
euro_lines = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key=e297e933c3ad47d71ec1626c299e",usecols=['player_name','datagolf_base_history_fit'])

# bring together api data above
dg_odds = pd.concat([real_odds,agg_lines,euro_lines], axis=1).T.drop_duplicates().T
dg_odds.columns = ['player_name','real_odds','agg_line','euro_line']
dg_odds['implied_prob'] = 1 / dg_odds.euro_line
dg_odds['ev'] = dg_odds['implied_prob'] * dg_odds['euro_line'] -1

# dg_odds = dg_odds[['player_name','real_odds','agg_line']]
# # calculate and add 'ev' feature
# dg_odds['implied_prob'] = dg_odds['real_odds'].fillna(0).apply(implied_probability)
# dg_odds['ev'] = dg_odds['implied_prob'] * dg_odds['euro_line'] -1
# # dg_odds = dg_odds[['player_name','real_odds','agg_line','ev']].convert_dtypes().round(2)
# dg_odds['agg_line'] = dg_odds['agg_line'].astype(int)

# dg_odds = dg_odds[['player_name','real_odds','agg_line','ev']]
# dg_odds = dg_odds.convert_dtypes()

dg_odds

In [ ]:
df.info()

In [ ]:
def american_to_decimal(american_odds):
    if american_odds > 0:
        return (american_odds / 100) + 1
    elif american_odds < 0:
        return (-100 / american_odds) + 1
    else:
        return 1

def calculate_expected_value(df):
    # Convert American odds to decimal odds
    df['real_odds_decimal'] = df['real_odds'].apply(american_to_decimal)
    df['book_odds_decimal'] = df['agg_line'].apply(american_to_decimal)
    
    # Calculate expected value
    df['expected_value'] = (1 / df['real_odds_decimal'] - 1) - (1 / df['book_odds_decimal'] - 1)
    
    # Drop temporary decimal odds columns
    df.drop(columns=['real_odds_decimal', 'book_odds_decimal'], inplace=True)
    
    return df

In [ ]:
calculate_expected_value(df).sort_values('expected_value',ascending=False)

In [ ]:
# dg decimal odds for calculating ev
dec_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key={dg_key}")#,usecols=['player_name','datagolf_base_history_fit'])


real_odds = dec_odds[['player_name','datagolf_base_history_fit']]
agg_lines = dec_odds[books].T.mean().to_frame() 
dg_dec_odds = pd.merge(real_odds, agg_lines, left_index=True, right_index=True)
dg_dec_odds.columns = ['player_name','real_dec_odds','real_dec_agg']
dg_dec_odds

In [ ]:
dg_dec_odds['implied_prob'] = dg_dec_odds['real_dec_odds']

In [22]:
# constants
books = ['betmgm', 'draftkings', 'bovada', 'betway','caesars']

# api calls
dg_outrights_data = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key={dg_key}")
dec_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key={dg_key}")


# get dg 'real' odds, industry aggregate odds in american/moneyline and euro/decimal formats
real_odds = dg_outrights_data[['player_name','datagolf_base_history_fit']]
agg_lines = dg_outrights_data[books].T.mean().to_frame()
agg_dec_lines = dec_odds[books].T.mean().to_frame()

# merge together, fix headers, drop nulls
df = pd.merge(real_odds, agg_lines, left_index=True, right_index=True) 
df = pd.merge(df,agg_dec_lines,left_index=True, right_index=True).T.drop_duplicates().T
df.columns = ['player_name','real_odds','agg_line','agg_dec_line']
df = df.dropna()

# add expected value column and clean datatypes
df['implied_prob'] = df['real_odds'].apply(implied_probability) 
df['ev'] = df['implied_prob'] * df['agg_dec_line'] -1
df = df[['player_name','real_odds','agg_line','ev']].convert_dtypes().round(2)
df['agg_line'] = df['agg_line'].astype(int)

# flip first/last names
df['player_name'] = fix_names(df['player_name'])

print(df.info())
df#[:20]#.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85 entries, 0 to 85
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_name  85 non-null     string
 1   real_odds    85 non-null     Int64
 2   agg_line     85 non-null     int32
 3   ev           85 non-null     Float64
dtypes: Float64(1), Int64(1), int32(1), string(1)
memory usage: 3.2 KB
None

          player_name  real_odds  agg_line    ev
0   Scottie Scheffler      -1973     -5375 -0.03
1   Bryson DeChambeau       -759      -806  -0.0
2        Ludvig Aberg       -143      -217 -0.14
3      Tyrrell Hatton       -153      -216 -0.11
4        Rory McIlroy       -162      -276 -0.15
..                ...        ...       ...   ...
80      Gary Woodland       8458      3420 -0.59
81       Zach Johnson      11646      6220 -0.46
83        Nick Taylor       8949      5125 -0.42
84              la De      34332     19333 -0.44
85        Vijay Singh      68003     15125 -0.78

[85 rows x 4 columns]

In [21]:
df.style.background_gradient(cmap="gist_heat", subset=['ev'])

In [ ]:
dg_odds = df.copy()

# fix names and column headers
dg_odds['player_name'] = fix_names(dg_odds)
# dg_odds['real_odds'] = dg_odds['real_odds'].apply(plus_prefix)
# dg_odds['agg_line'] = dg_odds['agg_line'].apply(plus_prefix)

dg_odds.columns = ['Player','Odds','Agg','EV']
dg_odds.sort_values('EV',ascending=True)

# styled_df = dg_odds.style.background_gradient(cmap="gist_heat", subset=['EV']).format(precision=2)
# styled_df

In [ ]:
dg_outrights_data = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key={dg_key}")
books = ['betmgm', 'betfair', 'fanduel', 'draftkings', 'bovada','williamhill', 'betonline', 'unibet', 'bet365','betway', 'skybet', 'pointsbet']

# dg and book aggregates in moneyline form for all players all markets
real_odds = dg_outrights_data[['player_name','datagolf_base_history_fit']]
agg_lines = dg_outrights_data[books].T.mean().to_frame() 
dg_odds = pd.merge(real_odds, agg_lines, left_index=True, right_index=True) 

# dg decimal odds for calculating ev
dec_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key={dg_key}",usecols=['player_name','datagolf_base_history_fit'])

# merge
df = dg_odds.merge(dec_odds,left_index=True, right_index=True).rename(
            columns={
                # 'player_name':'player',
                'datagolf_base_history_fit':'real_odds',
                '0_x':'agg_line',
                '0_y':'agg_dec'
                }
                )
df

In [ ]:
dg_outrights_data = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=american&file_format=csv&key={dg_key}")
books = ['betmgm', 'betfair', 'fanduel', 'draftkings', 'bovada','williamhill', 'betonline', 'unibet', 'bet365','betway', 'skybet', 'pointsbet']

# dg and book aggregates in moneyline form for all players all markets
real_odds = dg_outrights_data[['player_name','datagolf_base_history_fit']]
agg_lines = dg_outrights_data[books].T.mean().to_frame() 
dg_odds = pd.merge(real_odds, agg_lines, left_index=True, right_index=True) 

# dg decimal odds for calculating ev
dec_odds = pd.read_csv(f"https://feeds.datagolf.com/betting-tools/outrights?tour=pga&market={market_type}&odds_format=decimal&file_format=csv&key={dg_key}",usecols=['player_name','datagolf_base_history_fit'])

# merge
df = dg_odds.merge(dec_odds,left_index=True, right_index=True).T.drop_duplicates().T

df.columns = ['player_name','real_odds','agg_line','euro_line']
df = df.dropna()

df['implied_prob'] = df['real_odds'].apply(implied_probability)
df['ev'] = df['implied_prob'] * df['euro_line'] -1
df = df[['player_name','real_odds','agg_line','ev']].convert_dtypes().round(2)

df